#include "classes.h"

namespace
{

enum PLAYERCLASS
{
	PLAYERCLASS_INVALID = -1,
	PLAYERCLASS_NONE = 0,

	START_HUMANCLASS,
	PLAYERCLASS_MERCENARY,
	PLAYERCLASS_MEDIC,
	PLAYERCLASS_HERO,
	PLAYERCLASS_ENGINEER,
	PLAYERCLASS_SOLDIER,
	PLAYERCLASS_NINJA,
	PLAYERCLASS_SNIPER,
	PLAYERCLASS_SCIENTIST,
	PLAYERCLASS_BIOLOGIST,
	PLAYERCLASS_LOOPER,
	END_HUMANCLASS,

	START_INFECTEDCLASS,
	PLAYERCLASS_SMOKER,
	PLAYERCLASS_BOOMER,
	PLAYERCLASS_HUNTER,
	PLAYERCLASS_BAT,
	PLAYERCLASS_GHOST,
	PLAYERCLASS_SPIDER,
	PLAYERCLASS_GHOUL,
	PLAYERCLASS_SLUG,
	PLAYERCLASS_VOODOO,
	PLAYERCLASS_WITCH,
	PLAYERCLASS_UNDEAD,
	PLAYERCLASS_TANK,
	END_INFECTEDCLASS,

	NB_PLAYERCLASS,
	NB_HUMANCLASS = END_HUMANCLASS - START_HUMANCLASS - 1,
	NB_INFECTEDCLASS = END_INFECTEDCLASS - START_INFECTEDCLASS - 1,
};

}

int toNetValue(EPlayerClass C)
{
	if (C == EPlayerClass::None)
		return PLAYERCLASS_NONE;

	int Value = static_cast<int>(C);
	if (IsInfectedClass(C))
	{
		constexpr int InfectedClassOffset = PLAYERCLASS_SMOKER - static_cast<int>(EPlayerClass::Smoker);
		return Value + InfectedClassOffset;
	}
	else
	{
		constexpr int HumanClassOffset = PLAYERCLASS_MERCENARY - static_cast<int>(EPlayerClass::Mercenary);
		return Value + HumanClassOffset;
	}
}
